export interface AccidentQuery {
    sy?: string,
    ey?: string,
    sev?: string,
    injt?: number,
    city?: string,
    st?: string,
    rd?: string,
    rds?: string,
    sex?: number,
    age?: string,
    pt?: string,
    dn?: string,
    mn?: string,
    acc?: string,
    vcl?: string,
    rt?: string,
    sp?: string,
    rw?: string,
    ml?: string,
    ol?: string,
    p1?: string,
    p2?: string,
    gb?: string,
    gb2?: string,
    proj? : string,
    sort?: string, 
    lim?: string,
  };
